Add CSS setings and body general style
NondasNF/landing-page-challenge pull request #1
Opened 2022-02-08 12:05 UTC by NondasNF

ITCSS structure with some settings, resets and elements.

2022-02-08 12:44 UTC, iagodahlem requested changes

2022-02-08 12:44 UTC, iagodahlem commented on src/styles/index.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap');
Vamo evitar de fazer imports de fonts no CSS, apesar disso ser aplicavel pra todas as paginas, costuma ser mais lento e trava o carregamento do CSS, já que o browser precisa primeiro fazer download do arquivo de CSS, pra então enxergar esse import e começar a fazer download da fonte tambem.

2022-02-08 12:44 UTC, iagodahlem commented on src/styles/index.css
> +
A ideia é organizar cada camada da pirâmide em pastas e arquivos separados, ai o index.css serve só pra fazer imports de outros arquivos. Conforme os exemplos existentes. Tu precisa criar uma camada para as variáveis e outra pros elementos.

2022-02-08 12:44 UTC, iagodahlem commented on src/styles/index.css
> +  box-sizing:inherit;
Não precisa de box-sizing explicito aqui. O body já vai herdar isso diretamente como estamos usando o seletor universal pra setar o box-sizing de todos os elementos.

2022-02-09 01:31 UTC, iagodahlem requested changes

2022-02-09 01:31 UTC, iagodahlem commented on src/styles/elements/_body.css
> +body{
💅

```suggestion
body {
```

2022-02-09 01:31 UTC, iagodahlem commented on src/styles/generic/_resets.css
> +  box-sizing:border-box;
O box-sizing já esta sendo no setado no arquivo especifico dele, não é necessário aqui.

2022-02-09 11:53 UTC, NondasNF commented on src/styles/generic/_resets.css
> +  box-sizing:border-box;
Acho que eu havia entendido errado, acreditava que eu deveria setar ele de alguma forma

2022-02-09 12:19 UTC, iagodahlem approved these changes

2022-02-09 12:26 UTC, merged